/**
 * It's auth router module. It's used to handle all the auth related routes.
 */

const Router = require('koa-router');
const router = new Router();

// login route, get user info from request body, and query in db
// return the token if the user is valid, token is generated by jwt
router.post('/login', async (ctx, next) => {
	// get user info (username and password) from request body
	const user = ctx.request.body;
	// query the user in db
	const result = await ctx.db.collection('users').findOne(user);
	// if the user is valid
	if (result) {
		// generate the token
		const token = ctx.jwt.sign({
			data: user,
			exp: Math.floor(Date.now() / 1000) + (60 * 60)
		}, ctx.config.jwtSecret);
		// set the response body
		ctx.body = {
			token: token
		};
		// set the response status
		ctx.status = 200;
		// log the message
	} else {
		// set the response body
		ctx.body = {
			message: 'Invalid username or password.'
		};
		// set the response status
		ctx.status = 401;
		// log the message
	}

	await next();
});




// export the router
module.exports = router;